### ISSUE TITLE
Good example, but not working

### ISSUE THREAD

**Issue by ypwu1** [mohuishou/blog-code#1]
https://github.com/mohuishou/blog-code/blob/fbcb038347ae54aa6cbdac02a70d373bc2712ae1/02-k8s-operator/05-node-pool-operator/api/v1/nodepool_types.go#L69

试了一试，好像是node 和n 不是同一个对象， 返回的应该是n，而不是node吧。

**Comment by mohuishou** [comment]
感谢反馈，已修复，之前 07 是正常的
